"""
Individual tests for AMI models.

Original Author: David Banas <capn.freako@gmail.com>

Original Date:   April 2, 2026

Copyright (c) 2026 David Banas; All rights reserved World wide.
"""

import platform

from abc     import ABC, abstractmethod
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing  import Optional, Sequence

import em

from reportlab.lib.units    import inch
from reportlab.platypus     import Flowable, Image, ListFlowable, Paragraph

from ..ami.model        import AMIModel, OUT_RESP_INIT
from ..ami.parser       import AMIParamConfigurator
from ..ibis.model       import Model
from ..util.plot        import plt
from ..util.reportlab   import (
    bold, fixed, page_break, spacer, preformatted,
    P, H2, H3, H4, H5)

from .ami_tests_helpers import (
    AmiTestHelper, AmiTestHelperInitVsGetwave,
    AmiTestHelperSamplesPerBit, AmiTestHelperGetwaveInputLength, 
    plot_sweep)
from .test_defs         import TestSweep, TestSweeper
from .util              import get_all_sweepers


FIG_X_DFLT = 6.0
FIG_Y_DFLT = 4.0
DEBUG = False


class AmiTester(ABC):
    "Abstract class defining the structure and default behavior of an IBIS-AMI model tester."

    # Properties
    # - Defaults set by this base class `__init__()` function.
    _ami_model: AMIModel

    @property
    def ami_model(self):
        return self._ami_model

    _pcfg: AMIParamConfigurator

    @property
    def pcfg(self):
        return self._pcfg

    _test_sweepers: list[TestSweeper] = []

    @property
    def test_sweepers(self):
        return self._test_sweepers

    _fig_x: float = 6.0

    @property
    def fig_x(self):
        return self._fig_x

    _fig_y: float = 4.0

    @property
    def fig_y(self):
        return self._fig_y

    _init_ok: bool = False      # Flags suitability of `AMI_Init()` function.

    @property
    def init_ok(self):
        return self._init_ok

    _getwave_ok: bool = False   # Flags suitability of `AMI_GetWave()` function.

    @property
    def getwave_ok(self):
        return self._getwave_ok
    
    # - Not set by this base class `__init__()` function.
    #   Subclass must override if defaults here are not appropriate.
    _msg: str = ""      # Used for general purpose status/debugging.

    @property
    def msg(self):
        return self._msg
    
    _preamble: list[Flowable] = []  # Any desired introductory text for report body.

    @property
    def preamble(self):
        return self._preamble

    @preamble.setter
    def preamble(self, value):
        if not isinstance(value, list):
            raise TypeError(f"New value for `preamble` needs type `list[Flowable]` not {type(value)}.")
        if len(value) > 0:
            if not isinstance(value[0], Flowable):
                raise TypeError(f"New value for `preamble` needs type `list[Flowable]` not `list[{type(value[0])}]`.")
        self._preamble = value

    @property
    def helper(self) -> Optional[AmiTestHelper]:
        "Each subclass must define its own test helper if it needs one."
        return None

    # Initialization
    def __init__(
        self,
        ami_model: AMIModel, pcfg: AMIParamConfigurator,
        test_sweepers: list[TestSweeper],
        fig_x: float = FIG_X_DFLT, fig_y: float = FIG_Y_DFLT,
    ) -> None:
        """
        The ``__init__()`` function of an ``AmiTester`` subclass should, in order:

        1. Call ``super().__init__()``, to ensure correct/complete instance construction
        and establish sensible default values for ``_init_ok`` and ``_getwave_ok``,
        based on the given model's contents.

        2. Optionally, determine whether calling the model's ``AMI_Init()`` function is appropriate,
        setting ``self._init_ok`` accordingly.

        3. Optionally, determine whether calling the model's ``AMI_GetWave()`` function is appropriate,
        setting ``self._getwave_ok`` accordingly.

        4. Set ``self._preamble`` appropriately for the given model.

        Args:
            ami_model: The AMI model to be tested by this ``AmiTester`` subclass instance.
            pcfg: The AMI parameter configurator for the given AMI model.
            test_sweepers: The parameter sweeper classes to use.

        Keyword Args:
            fig_x: x-dimension of any plots generated by this tester.
            fig_y: y-dimension of any plots generated by this tester.

        Notes:
            1. The default implementation determines the correct values for
            ``_init_ok`` and ``_getwave_ok`` very simply as

                ``self._init_ok = ami_model.returns_impulse``
                ``self._getwave_ok = ami_model.has_getwave``

            If your subclass needs more sophisticated reasoning, to make these choices,
            you should encode that in your ``__init__()`` function.
        """

        # Stash given parameters in local variables.
        self._ami_model = ami_model
        self._pcfg = pcfg
        self._test_sweepers = test_sweepers
        self._fig_x = fig_x
        self._fig_y = fig_y

        # Set `_init_ok` and `_getwave_ok` defaults.
        init_returns_impulse = pcfg.fetch_param_val(["Reserved_Parameters", "Init_Returns_Impulse"])
        if init_returns_impulse is not None:
            self._init_ok = init_returns_impulse
        else:
            self._init_ok = True
        self._getwave_ok = ami_model.has_getwave

        return

    # Execution
    def __call__(self):
        return self.ami_tst()

    def ami_tst(self) -> list[Flowable]:
        """
        Perform some test on an ``AMIModel`` instance,
        using several different parameter sweep groups.

        Returns:
            A list of _ReportLab_ ``Flowable``s comprising the results of this test.
        """

        ami_model = self._ami_model
        pcfg = self._pcfg
        test_sweepers = self._test_sweepers
        fig_x = self._fig_x
        fig_y = self._fig_y

        flowables: list[Flowable] = [page_break]
        flowables.extend(self.preamble)
        flowables.append(spacer)
        for mod_doc, test_sweeps in test_sweepers:
            _mod_doc: str = mod_doc or "(No module description)"
            p = Paragraph(_mod_doc, H3)
            p.keepWithNext = True
            flowables.append(p)
            for test_sweep in test_sweeps:
                sweep_desc: str = test_sweep.__doc__ if test_sweep.__doc__ else "(No class description)"
                p = Paragraph(sweep_desc, H4)
                p.keepWithNext = True
                flowables.append(p)
                # ToDo: Pass `init_ok` and `getwave_ok` to helpers.
                if self.helper:
                    flowables.extend(plot_sweep(
                        self.helper, ami_model, pcfg, test_sweep,
                        fig_x=fig_x, fig_y=fig_y))
        return flowables


class AmiTestLinearityChecker(AmiTester):
    "Check ``AMI_Init()`` for linearity."

    preamble = [
        Paragraph(f"{fixed('AMI_Init()')} Linearity Check", H2),
        Paragraph(f"Here, we check that the {fixed('AMI_Init()')} function is linear."),
        spacer,
        Paragraph(
            f"{bold('Note:')} There is no requirement that the {fixed('AMI_GetWave()')} \
            function exhibit linearity. In fact, the {fixed('AMI_GetWave()')} function is \
            often used to capture non-linear behavior.", P),
        spacer,
        Paragraph(f"Compare each pair of red and blue traces below. \
                  If the model's {fixed('AMI_Init()')} function is truly linear, \
                  then the two should look identical.", P),
    ]

    def ami_tst(self) -> list[Flowable]:
        if not self.init_ok:
            return [Paragraph("This model's AMI_Init() function does not return an impulse response.", P)]

        ami_model = self.ami_model
        pcfg = self.pcfg
        test_sweepers = self.test_sweepers
        fig_x = self.fig_x
        fig_y = self.fig_y

        flowables: list[Flowable] = [page_break]
        flowables.extend(self.preamble)
        flowables.append(spacer)
        for mod_doc, test_sweeps in test_sweepers:
            _mod_doc: str = mod_doc or "(No module description)"
            p = Paragraph(_mod_doc, H3)
            p.keepWithNext = True
            flowables.append(p)
            for test_sweep in test_sweeps:
                sweep_desc: str = test_sweep.__doc__ if test_sweep.__doc__ else "(No class description)"
                p = Paragraph(sweep_desc, H4)
                p.keepWithNext = True
                flowables.append(p)
                for test_def in test_sweep().test_sweep():
                    p = Paragraph(preformatted(f"\t{test_def.description}:"), P)
                    p.keepWithNext = True
                    flowables.append(p)
                    # Test model against full channel response.
                    initializer = pcfg.get_init(
                        test_def.sim_params["bit_time"],
                        test_def.sim_params["sample_interval"],
                        test_def.sim_params["channel_response"],
                        test_def.ami_params
                    )
                    ami_model.initialize(initializer)
                    model_resps = ami_model.get_responses(nbits=test_def.sim_params["nbits"])
                    t, _, _, resp_to_sum, _, _ = model_resps[OUT_RESP_INIT]
                    fig = plt.figure(figsize=(fig_x, fig_y))
                    plt.plot(t * 1e9, resp_to_sum, label="Response to Sum")
                    # Test model against half channel response.
                    initializer.channel_response = [x / 2 for x in initializer.channel_response]
                    ami_model.initialize(initializer)
                    model_resps = ami_model.get_responses(nbits=test_def.sim_params["nbits"])
                    t, _, _, sum_of_resps, _, _ = model_resps[OUT_RESP_INIT]
                    sum_of_resps *= 2
                    plt.plot(t * 1e9, sum_of_resps, label="Sum of Responses")
                    plt.title("Comparing Pulse Responses")
                    plt.xlabel("Time (ns)")
                    plt.ylabel("p(t) (V)")
                    plt.legend()
                    with NamedTemporaryFile(suffix='.jpg', delete=False) as tmp_file:
                        plt.savefig(tmp_file)
                        flowables.append(Image(tmp_file.name, width=fig_x*inch, height=fig_y*inch))
                    plt.close()
                flowables.append(spacer)

        return flowables


class AmiTestInitVsGetwave(AmiTester):
    "Compare output from ``AMI_Init()`` and ``AMI_GetWave()`` functions."

    helper = AmiTestHelperInitVsGetwave(DEBUG)

    preamble = [
        Paragraph("Init() vs. GetWave()", H2),
        Paragraph(
            "Here, we check to see that the fundamental responses of the model are the same \
            whether we call AMI_Init() or AMI_GetWave().", P),
        spacer,
        Paragraph(f"{bold('Note:')} This test is only possible for models that:", P),
        ListFlowable([
            Paragraph(f"have an {fixed('AMI_GetWave()')} function, and", P),
            Paragraph(f"return an impulse response from their {fixed('AMI_Init()')} function.", P),
        ], bulletType='bullet', bulletIndent=0.25*inch),
        spacer,
        Paragraph(f"{bold('Plot notes:')}", P),
        ListFlowable([
            Paragraph(f"Solid lines are {fixed('Init()')}; dashed are {fixed('GetWave()')}."),
            Paragraph("Step response shown at reduced brightness."),
        ], bulletFontSize=9),
        spacer,
        Paragraph(f"Compare the plots below. \
                  The {fixed('Init()')} (solid) and {fixed('GetWave()')} (dashed) plots \
                  should look nearly identical.", P),
        Paragraph(f"({bold('Note:')} Ignore the waveform before time zero; \
                  it`s not expected to match and is plotted only as a debugging aid.)", P),
    ]


class AmiTestSamplesPerBit(AmiTester):
    "Compare model response at different oversampling factors."

    helper = AmiTestHelperSamplesPerBit()

    preamble = [
        Paragraph("Samples per Bit", H2),
        Paragraph("Here, we test the model's sensitivity to the oversampling factor, \
                   i.e., number of samples per bit (or, symbol).", P),
        Paragraph("You should see very little difference between the 3 plots in any of the charts below.", P),
    ]


class AmiTestGetwaveInputLength(AmiTester):
    "Compare ``AMI_GetWave()`` outputs for different input lengths."

    helper = AmiTestHelperGetwaveInputLength()

    def ami_tst(self) -> list[Flowable]:
        preamble: list[Flowable] = [
            Paragraph(f"{fixed('AMI_GetWave()')} Input Length Sensitivity", H2),
            Paragraph(f"Sometimes, depending upon how it's implemented, the {fixed('AMI_GetWave()')} function \
                      may exhibit sensitivity to the length of its input. And this is undesireable. \
                      Here, we try to flush that out if it's occurring.", P),
        ]
        if self.ami_model.has_getwave:
            preamble.append(
                Paragraph("You should see very little difference, in either domain, \
                          between the various plots in any of the charts below.", P)
            )
            self.preamble = preamble
            return super().ami_tst()
        else:
            preamble.append(
                Paragraph(f"Model has no {fixed('AMI_GetWave()')} function.", P)
            )
            return preamble


def test_ami_model(
    model_name: str, model: Model,
    ibis_file: Path, test_sweeps_dir: Path,
    f_max: float = 40e9, f_step: float = 10e6
) -> list[Flowable]:
    """
    Test an individual IBIS-AMI model.

    Args:
        model_name: The name of the model to test.
        model: The IBIS-AMI model to test.
        ibis_file: Path to ``*.ibs`` file being tested.
        test_sweeps_dir: The top level directory containing all test sweep configurations.
            (Individual model sweepers will be found in:
            ``<test_sweeps_dir>``/``<ibis_file_relative_path.stem>``/``model_name>``/.)

    Keyword Args:
        f_max: Maximum frequency of interest (Hz).
            Default: 40 GHz
        f_step: Frequency increment (Hz).
            Default: 10 MHz

    Returns:
        A list of *ReportLab* ``Flowable``s describing the test results.
    """

    if not model.is_ami:
        return [Paragraph("Error: This model is not an IBIS-AMI model!", P)]

    # Try to fetch AMI files for this machine/system combination.
    machine = platform.machine().lower()
    match(machine):
        case "x86":
            ami_dict = model.ami_files.get('32-bit')
        case "x86_64":
            ami_dict = model.ami_files.get('64-bit')
        case "amd64":
            ami_dict = model.ami_files.get('64-bit')
        case "arm64":
            ami_dict = model.ami_files.get('64-bit')
        case _:
            return [Paragraph(f"Error: Unrecognized machine type: {machine}!", P)]
    system = platform.system().lower()
    match(system):
        case "windows":
            ami_files = ami_dict.get('win')
        case "linux":
            ami_files = ami_dict.get('lin')
        case "darwin":
            ami_files = ami_dict.get('lin')
        case _:
            return [Paragraph(f"Error: Unrecognized system type: {system}!", P)]
    if not ami_files:
        return [Paragraph(f"Error: Model does not provide AMI files for this machine/system combination: {machine}/{system}!", P)]

    flowables: list[Flowable] = [Paragraph("Basic Sanity Checking", H2)]

    # Attempt to create the AMI model and its configurator.
    ibis_file_dir = ibis_file.parent
    dll_file, ami_file = list(map(lambda f: ibis_file_dir / Path(f), ami_files))
    try:
        ami_model = AMIModel(str(dll_file))
    except Exception as err:
        return [Paragraph(str(err), P), Paragraph(f"Error loading AMI DLL/SO: {dll_file}!", P)]
    try:
        with open(ami_file, mode="r", encoding="utf-8") as pfile:
            pcfg = AMIParamConfigurator(pfile.read())
        if pcfg.ami_parsing_errors:
            flowables.append(
                Paragraph(preformatted(f"Non-fatal AMI file parsing errors:\n{pcfg.ami_parsing_errors}"),
                          P))
        has_getwave = pcfg.fetch_param_val(["Reserved_Parameters", "GetWave_Exists"]) or False
        ignore_bits = pcfg.fetch_param_val(["Reserved_Parameters", "Ignore_Bits"]) or 0
        returns_impulse = pcfg.fetch_param_val(["Reserved_Parameters", "Init_Returns_Impulse"]) or False
        has_ts4 = True if pcfg.fetch_param_val(["Reserved_Parameters", "Ts4file"]) else False
    except Exception as err:
        flowables.append(Paragraph(str(err), P))
        flowables.append(Paragraph(f"Error loading AMI parameter file: {ami_file}!", P))
        return flowables

    # Summarize results.
    flowables.append(Paragraph("Model import was successful.", P))
    if has_getwave:
        flowables.append(Paragraph("Model has a `AMI_GetWave()` function.", P))
        flowables.append(Paragraph(f"&nbsp;&nbsp;The first {ignore_bits} returned bits should be ignored.", P))
    else:
        flowables.append(Paragraph("Model has no `AMI_GetWave()` function.", P))
    if returns_impulse:
        flowables.append(Paragraph("Model's `AMI_Init()` function returns an impulse response.", P))
    else:
        flowables.append(Paragraph("Model's `AMI_Init()` function does not return an impulse response.", P))
    if has_ts4:
        flowables.append(Paragraph("Model includes on-die S-parameters.", P))
    else:
        flowables.append(Paragraph("Model does not include on-die S-parameters.", P))

    # Fetch parameter sweepers or create a defaults template.
    flowables.append(Paragraph("AMI Parameter Sweeps Info", H2))
    model_sweeps_dir = test_sweeps_dir / ibis_file.parent.relative_to(test_sweeps_dir.parent) / ibis_file.stem / model_name
    test_sweepers = get_all_sweepers(model_sweeps_dir)
    if test_sweepers:
        flowables.append(Paragraph("Using parameter sweep definitions in:", P))
        flowables.append(Paragraph(preformatted(f"\t{model_sweeps_dir}"), P))
    else:
        model_sweeps_dir.mkdir(parents=True, exist_ok=True)
        dflt_test_sweep_file = model_sweeps_dir / "defaults_template.py"
        # Make default sweep file, using template, here.
        em_file = Path(__file__).parent.joinpath("generic_test_sweep.py.em")
        with open(dflt_test_sweep_file, "w", encoding="utf-8") as o_file:
            interpreter = em.Interpreter(
                output=o_file,
                globals={
                    "ami_params": pcfg.input_ami_params,
                },
            )
            try:
                with open(em_file, "rt", encoding="utf-8") as in_file:
                    interpreter.file(in_file)
            finally:
                interpreter.shutdown()
        flowables.append(Paragraph(preformatted("\n".join(
            [f"Did not find any test sweep definitions in:\n\t{model_sweeps_dir}.",
             f"So, a default test sweep definition file for this model has been created in:\n\t{dflt_test_sweep_file}",
             "You can use this file as a template for expanding your test suite for this model.",
             "The newly created file has instructions for doing this."
            ])), P))
        test_sweepers = get_all_sweepers(model_sweeps_dir)
        if not test_sweepers:
            raise RuntimeError(f"Attempt to create a default sweep definition file:\n\t{dflt_test_sweep_file}\nfailed.")

    # Run specific tests.
    testers: Sequence[AmiTester] = [
        AmiTestInitVsGetwave(ami_model, pcfg, test_sweepers),
        AmiTestSamplesPerBit(ami_model, pcfg, test_sweepers),
        AmiTestGetwaveInputLength(ami_model, pcfg, test_sweepers),
        AmiTestLinearityChecker(ami_model, pcfg, test_sweepers),
    ]

    for tester in testers:
        flowables.extend(tester.ami_tst())

    return flowables
